<a href="https://colab.research.google.com/github/JoCur/Single-neural-network/blob/main/Simple_Neural_Network_to_recogn_patterns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


1) Understanding Class = Object (attributes & methods)

In [2]:
#Class attribute (belongs to the class)-> We create a class = Snake and assign certain properties, for example, "name"

class Snake:
  name="python"

In [3]:
snake = Snake()


In [4]:
print(snake.name)

python


In [5]:
#class method -> actions you can perform with the object. (in this case, changing the name)

class Snake:
  name = "python"

  def change_name (self, new_name):
    self.name= new_name # access the class attribute with the self keyword


In [6]:
snake = Snake()
snake.change_name("anaconda")
print(snake.name)

anaconda


2) Instance attributes in python and the init method

You can also provide the values for the attributes at runtime. This is done by defining the attributes inside the init method. The following example illustrates this.

In [1]:
class Snake:

    def __init__(self, name):
        self.name = name

    def change_name(self, new_name):
        self.name = new_name

In [ ]:
python = Snake("python")

print(python.name)

python


In [ ]:
python.change_name("violet")
python.name

'violet'

# **Modelling one single neuron**:
 


In [11]:
from numpy import exp, array, random,dot


1) We create the neural network using "class" and define an attribute called weights, and methods to train the neuron on getting accurate outputs.

In [22]:
class neural_network:
   #Assign random values to the attribute "weights"
  def __init__(self):
    random.seed(1)
    self.weights = 2*random.random((3,1))-1

  # Def sigmoid method to normalize the weighted sum of the inputs. (This function can map any value to a value from 0 to 1)
  def __sigmoid (self,x):
    return 1/(1+exp(-x))

  # Define think method to calculate the sum product of the inputs and the randomly assigned weights.
  def think (self, inputs):
    result=self.__sigmoid(dot(inputs, self.weights))
    return result

  # Define the train method to iterate a num of times the calculation of an output = the sum product of the inputs and random weights, 
  # get the diff between the outputs in the training set (transposed) and the calculated output (error), 
  # and adjust the weights so that when multiplied by the inputs, the result approximates more to the real-life outputs each time.
  def train (self, inputs, outputs, num):
    for iteration in range (num):
      output = self.think(inputs)
      error= outputs.T -output
      adjustment = dot (inputs.T, error*output*(1-output))
      self.weights += adjustment

2) We create a variable of class "neural network"

In [23]:
network= neural_network()

In [24]:
# Print weights to check the numbers randomly assigned
network.weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [25]:
# Define the training set (3 inputs and 1 output):
inputs= array([[1,1,1], [1,0,1], [0,1,1]])

outputs= array ([[1,1,0]])

In [26]:
# By calling the method "train", we repeat the iteration 10 times to adjust the weights so they better represent the relationship between the inputs and the outputs.
network.train(inputs, outputs, 10)

In [27]:
# Print weights after training, to verify the adjusted values.
network.weights

array([[ 1.54925248],
       [ 0.0607038 ],
       [-0.42348049]])

In [ ]:
# Applying the method "think" with a new set of 3 inputs, we get the estimated output. (The excpected result would be = 1, since the output in the training set is always = to the first element in the 3d array of inputs)
network.think(array([1,0,0]))

array([0.82480574])

Understanding how figures change along the training process:

The operations the neuron performs in each repetition are:

In [44]:
# The weights of the neuron are defined randonmly:
random.seed(1) 
weights1 = 2*random.random((3,1))-1
print("Initial weights: \n{}".format(weights1))

#The training set is:
inputs1= array([[1,1,1], [1,0,1], [0,1,1]])

outputs1= array ([[1,1,0]])

#TAKE THE INPUTS & OUTPUTS AND TRAIN A NUM OF TIMES

for i in range(10):
  print("\nIteration nº {}".format(i+1))

  #Calculate the output as the normalized weighted sum product of the inputs and weights

  output1= 1/(1+exp(-dot(inputs1,weights1)))
  print("\nEstimated output: \n{}".format(output1))

  #Calculate the error
  error1 = outputs1.T-output1
  print("\nError (diff between estimated output & outputs from training set): \n{}".format(error1))

  #Get the adjustment
  adjustment1 = dot (inputs1.T, error1*output1*(1-output1))
  print("\nAdjustment: \n{}".format(adjustment1))

  #Improve weights values
  weights1 += adjustment1
  print("\nAdjusted weights: \n{} ".format(weights1))

print("Weights in the last rep match the neuron weights after training 10 times with the same set")

Initial weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]

Iteration nº 1

Estimated output: 
[[0.3262757 ]
 [0.23762817]
 [0.36375058]]

Error (diff between estimated output & outputs from training set): 
[[ 0.6737243 ]
 [ 0.76237183]
 [-0.36375058]]

Adjustment: 
[[0.28621005]
 [0.06391297]
 [0.20202504]]

Adjusted weights: 
[[ 0.12025406]
 [ 0.50456196]
 [-0.79774622]] 

Iteration nº 2

Estimated output: 
[[0.45687487]
 [0.33682126]
 [0.42722449]]

Error (diff between estimated output & outputs from training set): 
[[ 0.54312513]
 [ 0.66317874]
 [-0.42722449]]

Adjustment: 
[[0.28290722]
 [0.03022777]
 [0.17836379]]

Adjusted weights: 
[[ 0.40316127]
 [ 0.53478973]
 [-0.61938242]] 

Iteration nº 3

Estimated output: 
[[0.57897536]
 [0.44615433]
 [0.47886443]]

Error (diff between estimated output & outputs from training set): 
[[ 0.42102464]
 [ 0.55384567]
 [-0.47886443]]

Adjustment: 
[[ 0.2394858 ]
 [-0.01687201]
 [ 0.11998361]]

Adjusted weights: 
[[ 0.64264708]
 [ 0.517917

## **DECONSTRUCTION ♈**

The idea is to emulate the first training rep, as the process performed is the same each time.

The values stored in each of the arrays match the ones from Iteration 1 above.

In [45]:
# ASSIGN RANDOM WEIGHTS from 0 to 1 as the initial weights (see that values match the neuron's weights)

random.seed(1) #single neuron with 3 inputs and 1 output, and assign random weight
weights1 = 2*random.random((3,1))-1
weights1

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [46]:
#Define the training set:

inputs1= array([[1,1,1], [1,0,1], [0,1,1]])

outputs1= array ([[1,1,0]])

In [47]:
# Calculate x, as the sum product of the matrices INPUTS X WEIGHTS []
x= dot(inputs, weights)
x

array([[-0.72507825],
       [-1.16572724],
       [-0.55912226]])

In [48]:
# Use sigmoid to normalize the weighted sum:
result1 = 1/(1+exp(-x))
result1

array([[0.3262757 ],
       [0.23762817],
       [0.36375058]])

In [49]:
#Transpose the outputs to calculate the error
outputs1.T

array([[1],
       [1],
       [0]])

In [50]:
#Calculate the error:
error1=outputs1.T-result1
error1

array([[ 0.6737243 ],
       [ 0.76237183],
       [-0.36375058]])

In [51]:
# Get the values to be multiplied by the inputs to get the adjustments
error1*result1*(1-result1)

array([[ 0.14809799],
       [ 0.13811206],
       [-0.08418501]])

In [52]:
#Transpose the inputs 
inputs1.T

array([[1, 1, 0],
       [1, 0, 1],
       [1, 1, 1]])

In [53]:
# Get the adjustments
adjustment1 = dot(inputs.T, error1*result1*(1-result1))
adjustment1

array([[0.28621005],
       [0.06391297],
       [0.20202504]])

In [54]:
weights1+= adjustment1
weights1 

array([[ 0.12025406],
       [ 0.50456196],
       [-0.79774622]])

Finally, when trained a higher number of times, it approaches the expected result of 1 quite accurately

In [58]:

inputs= array([[1,1,1], [1,0,1], [0,1,1]])

outputs= array ([[1,1,0]])

network.train(inputs, outputs, 1000000)

network.think(array([1,0,0]))

array([0.99999888])