<a href="https://colab.research.google.com/github/JoCur/Single-neural-network/blob/Clean-code/Simple_Neural_Network_to_recogn_patterns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Intro to Class = Object (EXAMPLE)

In [ ]:
#Class attribute (belongs to the class)-> We create a class = Snake and assign a name to it.

class Snake:
  name="python"

In [ ]:
snake = Snake()


In [ ]:
print(snake.name)

python


In [ ]:
#class method -> it allows to access the attribute and change it (in this case, the name)

class Snake:
  name = "python"

  def change_name (self, new_name):
    self.name= new_name # access the class attribute with the self keyword


In [ ]:
snake = Snake()
snake.change_name("anaconda")
print(snake.name)

anaconda


Instance attributes in python and the init method

You can also provide the values for the attributes at runtime. This is done by defining the attributes inside the init method. The following example illustrates this.

In [ ]:
class Snake:

    def __init__(self, name):
        self.name = name

    def change_name(self, new_name):
        self.name = new_name

In [ ]:
python = Snake("python")

print(python.name)

python


In [ ]:
python.change_name("violet")
python.name

'violet'

# **Modelling one single neuron**:
3 inputs
1 output
random weight 


In [ ]:
from numpy import exp, array, random,dot


In [ ]:
class neural_network:
  def __init__(self):
    random.seed(1) #single neuron with 3 inputs and 1 output, and assign random weight
    self.weights = 2*random.random((3,1))-1

  def __sigmoid (self,x):
    return 1/(1+exp(-x))

  def think (self, inputs):
    result=self.__sigmoid(dot(inputs, self.weights))
    return result

  def train (self, inputs, outputs, num):
    for iteration in range (num):
      output = self.think(inputs)
      error= outputs.T -output
      adjustment = dot (inputs.T, error*output*(1-output))
      self.weights += adjustment

In [ ]:
network= neural_network()

In [ ]:
network.weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [ ]:
#training set:
inputs= array([[1,1,1], [1,0,1], [0,1,1]])

outputs= array ([[1,1,0]])

In [ ]:
network.train(inputs, outputs, 10)

In [ ]:
network.weights

array([[ 1.54925248],
       [ 0.0607038 ],
       [-0.42348049]])

In [ ]:
network.think(array([1,0,0]))

array([0.82480574])

## **DECONSTRUCTION ♈**

In [ ]:
#ASSIGN RANDOM WEIGHTS from 0 to 1 as the initial weights

random.seed(1) #single neuron with 3 inputs and 1 output, and assign random weight
weights = 2*random.random((3,1))-1
weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [ ]:


#training set:
inputs1= array([[1,1,1], [1,0,1], [0,1,1]])

outputs1= array ([[1,1,0]])

In [ ]:
#USE THE DOT METHOD TO CALCULATE THE DOT PRODUCT OF MATRICES: INPUTS X WEIGHTS
x= dot(inputs, weights)
x

array([[-0.72507825],
       [-1.16572724],
       [-0.55912226]])

In [ ]:
#USE SIGMOID AS A HELPER TO NORMALIZE THE WEIGHTED SUM
result1 = 1/(1+exp(-x))
result1

array([[0.3262757 ],
       [0.23762817],
       [0.36375058]])

In [ ]:
outputs1.T

array([[1],
       [1],
       [0]])

In [ ]:
error1=outputs1.T-result1
error1

array([[ 0.6737243 ],
       [ 0.76237183],
       [-0.36375058]])

In [ ]:
error1*result1*(1-result1)

array([[ 0.14809799],
       [ 0.13811206],
       [-0.08418501]])

In [ ]:
inputs1.T

array([[1, 1, 0],
       [1, 0, 1],
       [1, 1, 1]])

In [ ]:
adjustment1 = dot(inputs.T, error1*result1*(1-result1))
adjustment1

array([[0.28621005],
       [0.06391297],
       [0.20202504]])

In [ ]:
weights+= adjustment1
weights 

array([[ 0.12025406],
       [ 0.50456196],
       [-0.79774622]])

In [ ]:
random.seed(1) #single neuron with 3 inputs and 1 output, and assign random weight
weights1 = 2*random.random((3,1))-1
print(weights1)

#training set:
inputs1= array([[1,1,1], [1,0,1], [0,1,1]])

outputs1= array ([[1,1,0]])

#TAKE THE INPUTS & OUTPUTS AND TRAIN A NUM OF TIMES
for i in range(10):
  print(i)
  output1= 1/(1+exp(-dot(inputs1,weights1)))
  print( output1)
  error1 = outputs1.T-output1
  print(error1)
  adjustment1 = dot (inputs1.T, error1*output1*(1-output1))
  print(adjustment1)
  weights1 += adjustment1
  print(weights1)



[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
0
[[0.3262757 ]
 [0.23762817]
 [0.36375058]]
[[ 0.6737243 ]
 [ 0.76237183]
 [-0.36375058]]
[[0.28621005]
 [0.06391297]
 [0.20202504]]
[[ 0.12025406]
 [ 0.50456196]
 [-0.79774622]]
1
[[0.45687487]
 [0.33682126]
 [0.42722449]]
[[ 0.54312513]
 [ 0.66317874]
 [-0.42722449]]
[[0.28290722]
 [0.03022777]
 [0.17836379]]
[[ 0.40316127]
 [ 0.53478973]
 [-0.61938242]]
2
[[0.57897536]
 [0.44615433]
 [0.47886443]]
[[ 0.42102464]
 [ 0.55384567]
 [-0.47886443]]
[[ 0.2394858 ]
 [-0.01687201]
 [ 0.11998361]]
[[ 0.64264708]
 [ 0.51791772]
 [-0.49939881]]
3
[[0.65952226]
 [0.53575095]
 [0.50462959]]
[[ 0.34047774]
 [ 0.46424905]
 [-0.50462959]]
[[ 0.19192407]
 [-0.04969141]
 [ 0.06577749]]
[[ 0.83457115]
 [ 0.46822631]
 [-0.43362133]]
4
[[0.70457424]
 [0.59891584]
 [0.50865038]]
[[ 0.29542576]
 [ 0.40108416]
 [-0.50865038]]
[[ 0.15783938]
 [-0.06563185]
 [ 0.03071485]]
[[ 0.99241053]
 [ 0.40259447]
 [-0.40290648]]
5
[[0.72950222]
 [0.64325134]
 [0.499922  ]]


In [ ]:
weights1

array([[ 1.54925248],
       [ 0.0607038 ],
       [-0.42348049]])

In [ ]:
input2= array([1,0,0])
result2=  1/(1+exp(-(dot(input2,weights1))))

result2

array([0.82480574])